### ISSUE TITLE
Adding compatibility with PHP 8.0.1?

### ISSUE THREAD

**Issue by dlogvin** [cloudcreativity/laravel-stripe#11]
I'm trying to implement the package on a new fresh project with the latest laravel version, although, I got PHP 8.0.1. The package is not compatible with this version of PHP.

**Comment by lindyhopchris** [comment]
Hi! Thanks for raising this - my apps are on PHP 7.4 so I didn't spot that this package hadn't been updated for PHP 8.

I've just tagged `0.5.1` which adds PHP 8 support.
